In [40]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('Clean15YearChennaiWeather.csv')
df=df.sort_values(['year','month','day_name','day_date','Start_hour'],ascending=[True,True,True,True,True])
df.head(3)

date       date_id  wind  \
508  Monday 14 September 2009, 00.00 — 06.00  1.252886e+12   5.0   
509  Monday 14 September 2009, 06.00 — 12.00  1.252908e+12   8.0   
510  Monday 14 September 2009, 12.00 — 18.00  1.252930e+12   6.0   

                  desc  temp    baro  hum         day  month  day_date  year  \
508    Passing clouds.  30.0  1009.0   82  2009-09-14      9        14  2009   
509             Clear.  35.0  1011.0   64  2009-09-14      9        14  2009   
510  Scattered clouds.  37.0  1007.0   53  2009-09-14      9        14  2009   

     day_name Start_hour End_hour  
508         0      00:00    06:00  
509         0      06:00    12:00  
510         0      12:00    18:00

In [41]:
df.columns

Index(['date', 'date_id', 'wind', 'desc', 'temp', 'baro', 'hum', 'day',
       'month', 'day_date', 'year', 'day_name', 'Start_hour', 'End_hour'],
      dtype='object')

In [42]:
df[['wind','temp','baro','hum']].corr()

wind      temp      baro       hum
wind  1.000000  0.547964  0.267167 -0.162249
temp  0.547964  1.000000 -0.216422 -0.829084
baro  0.267167 -0.216422  1.000000  0.726712
hum  -0.162249 -0.829084  0.726712  1.000000

In [43]:
df.isna().sum()

date           0
date_id        0
wind           0
desc           0
temp          30
baro           0
hum            0
day            0
month          0
day_date       0
year           0
day_name       0
Start_hour     0
End_hour       0
dtype: int64

In [44]:
from sklearn.impute import KNNImputer

temp_reshaped = df['temp'].values.reshape(-1, 1)

imputer = KNNImputer(n_neighbors=2)

temp_imputed = imputer.fit_transform(temp_reshaped)

df['temp'] = temp_imputed


In [45]:
train_features=['date_id', 'wind', 'desc', 'baro', 'hum', 'day',
       'month', 'day_date', 'year', 'day_name', 'Start_hour', 'End_hour']
test_features=['temp']


from sklearn_pandas import DataFrameMapper

df['desc']= df['desc'].fillna('missing', inplace=True)
df['desc'] = df['desc'].astype(str)

mapper = DataFrameMapper([
    (['month','wind','baro', 'hum'], None),
    ('desc',CountVectorizer(binary=True, ngram_range=(1, 2)))
])

X=mapper.fit_transform(df)
print(X)

[[9.000e+00 5.000e+00 1.009e+03 8.200e+01 1.000e+00]
 [9.000e+00 8.000e+00 1.011e+03 6.400e+01 1.000e+00]
 [9.000e+00 6.000e+00 1.007e+03 5.300e+01 1.000e+00]
 ...
 [7.000e+00 1.700e+01 1.000e+03 5.700e+01 1.000e+00]
 [7.000e+00 1.700e+01 1.000e+03 5.700e+01 1.000e+00]
 [7.000e+00 1.700e+01 1.000e+03 5.700e+01 1.000e+00]]


In [46]:
x = X.copy()
y = df[test_features].copy()

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=50)

In [47]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler(feature_range=(0,1))
X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

LinearRegression

In [48]:
from sklearn.linear_model import LinearRegression
import sklearn.metrics as sm

model=LinearRegression()
model.fit(X_train,y_train)
prediction = model.predict(X_test)
print('Variance score: %.2f' % model.score(X_test, y_test))
print('different: %.2f' % np.mean(np.absolute(prediction-y_test)))
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, prediction), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y_test, prediction), 2)) 

Variance score: 0.73
different: 1.44
Mean absolute error = 1.44
Mean squared error = 3.63


Decision Tree Regression

In [49]:
from sklearn.tree import DecisionTreeRegressor
dtree=DecisionTreeRegressor(random_state=0)
dtree.fit(X_train,y_train)
prediction2=dtree.predict(X_test)
print('Variance score: %.2f' % dtree.score(X_test, y_test))
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, prediction2), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y_test, prediction2), 2)) 

Variance score: 0.83
Mean absolute error = 0.76
Mean squared error = 2.3


Random Forest Regression

In [50]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

rnd=RandomForestRegressor(max_depth=90,random_state=0,n_estimators=100)
rnd.fit(X_train,y_train)
prediction3=rnd.predict(X_test)
print('Variance score: %.2f' % rnd.score(X_test, y_test))
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, prediction3), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y_test, prediction3), 2)) 
     

Variance score: 0.90
Mean absolute error = 0.62
Mean squared error = 1.3
